RailsExampleFromClas/config/routes.rb
Rails.application.routes.draw do
  resources :orders

  resources :customers

  resources :pumpkins

end

RailsExampleFromClas/app/models/customer.rb
class Customer < ActiveRecord::Base
	has_many :orders;
end

RailsExampleFromClas/app/models/order.rb
class Order < ActiveRecord::Base
	belongs_to(:customer);
end

RailsExampleFromClas/app/models/pumpkin.rb
class Pumpkin < ActiveRecord::Base
end

RailsExampleFromClas/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

RailsExampleFromClas/app/controllers/customers_controller.rb
class CustomersController < ApplicationController
  before_action :set_customer, only: [:show, :edit, :update, :destroy]

  # GET /customers
  # GET /customers.json
  def index
    @customers = Customer.all
  end

  # GET /customers/1
  # GET /customers/1.json
  def show
  end

  # GET /customers/new
  def new
    @customer = Customer.new
  end

  # GET /customers/1/edit
  def edit
  end

  # POST /customers
  # POST /customers.json
  def create
    @customer = Customer.new(customer_params)

    respond_to do |format|
      if @customer.save
        format.html { redirect_to @customer, notice: 'Customer was successfully created.' }
        format.json { render :show, status: :created, location: @customer }
      else
        format.html { render :new }
        format.json { render json: @customer.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /customers/1
  # PATCH/PUT /customers/1.json
  def update
    respond_to do |format|
      if @customer.update(customer_params)
        format.html { redirect_to @customer, notice: 'Customer was successfully updated.' }
        format.json { render :show, status: :ok, location: @customer }
      else
        format.html { render :edit }
        format.json { render json: @customer.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /customers/1
  # DELETE /customers/1.json
  def destroy
    @customer.destroy
    respond_to do |format|
      format.html { redirect_to customers_url, notice: 'Customer was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_customer
      @customer = Customer.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def customer_params
      params.require(:customer).permit(:name, :discount)
    end
end

RailsExampleFromClas/app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  before_action :set_order, only: [:show, :edit, :update, :destroy]

  # GET /orders
  # GET /orders.json
  def index
    @orders = Order.all
  end

  # GET /orders/1
  # GET /orders/1.json
  def show
  end

  # GET /orders/new
  def new
    #raise params.inspect
    customer = Customer.find(params["customer"])

    #@order = Order.new
    @order = customer.orders.build
  end

  # GET /orders/1/edit
  def edit
  end

  # POST /orders
  # POST /orders.json
  def create
    @order = Order.new(order_params)

    respond_to do |format|
      if @order.save
        format.html { redirect_to @order, notice: 'Order was successfully created.' }
        format.json { render :show, status: :created, location: @order }
      else
        format.html { render :new }
        format.json { render json: @order.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /orders/1
  # PATCH/PUT /orders/1.json
  def update
    respond_to do |format|
      if @order.update(order_params)
        format.html { redirect_to @order, notice: 'Order was successfully updated.' }
        format.json { render :show, status: :ok, location: @order }
      else
        format.html { render :edit }
        format.json { render json: @order.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /orders/1
  # DELETE /orders/1.json
  def destroy
    @order.destroy
    respond_to do |format|
      format.html { redirect_to orders_url, notice: 'Order was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_order
      @order = Order.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def order_params
      params.require(:order).permit(:customer_id, :placed_on)
    end
end

RailsExampleFromClas/app/controllers/pumpkins_controller.rb
class PumpkinsController < ApplicationController
  before_action :set_pumpkin, only: [:show, :edit, :update, :destroy]

  # GET /pumpkins
  # GET /pumpkins.json
  def index
    @pumpkins = Pumpkin.all
  end

  # GET /pumpkins/1
  # GET /pumpkins/1.json
  def show
  end

  # GET /pumpkins/new
  def new
    @pumpkin = Pumpkin.new
  end

  # GET /pumpkins/1/edit
  def edit
  end

  # POST /pumpkins
  # POST /pumpkins.json
  def create
    @pumpkin = Pumpkin.new(pumpkin_params)

    respond_to do |format|
      if @pumpkin.save
        format.html { redirect_to @pumpkin, notice: 'Pumpkin was successfully created.' }
        format.json { render :show, status: :created, location: @pumpkin }
      else
        format.html { render :new }
        format.json { render json: @pumpkin.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /pumpkins/1
  # PATCH/PUT /pumpkins/1.json
  def update
    respond_to do |format|
      if @pumpkin.update(pumpkin_params)
        format.html { redirect_to @pumpkin, notice: 'Pumpkin was successfully updated.' }
        format.json { render :show, status: :ok, location: @pumpkin }
      else
        format.html { render :edit }
        format.json { render json: @pumpkin.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /pumpkins/1
  # DELETE /pumpkins/1.json
  def destroy
    @pumpkin.destroy
    respond_to do |format|
      format.html { redirect_to pumpkins_url, notice: 'Pumpkin was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_pumpkin
      @pumpkin = Pumpkin.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def pumpkin_params
      params.require(:pumpkin).permit(:name, :color, :size, :price)
    end
end

RailsExampleFromClas/app/helpers/application_helper.rb
module ApplicationHelper
end

RailsExampleFromClas/app/helpers/customers_helper.rb
module CustomersHelper
end

RailsExampleFromClas/app/helpers/orders_helper.rb
module OrdersHelper
end

RailsExampleFromClas/app/helpers/pumpkins_helper.rb
module PumpkinsHelper
end

RailsExampleFromClas/app/views/customers/_form.html.erb
<%= form_for(@customer) do |f| %>
  <% if @customer.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@customer.errors.count, "error") %> prohibited this customer from being saved:</h2>

      <ul>
      <% @customer.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :discount %><br>
    <%= f.text_field :discount %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

RailsExampleFromClas/app/views/customers/edit.html.erb
<h1>Editing customer</h1>

<%= render 'form' %>

<%= link_to 'Show', @customer %> |
<%= link_to 'Back', customers_path %>

RailsExampleFromClas/app/views/customers/index.html.erb
<h1>Listing customers</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Discount</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @customers.each do |customer| %>
      <tr>
        <td><%= customer.name %></td>
        <td><%= customer.discount %></td>
        <td><%= link_to 'Show', customer %></td>
        <td><%= link_to 'Edit', edit_customer_path(customer) %></td>
        <td><%= link_to 'Destroy', customer, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Customer', new_customer_path %>

RailsExampleFromClas/app/views/customers/new.html.erb
<h1>New customer</h1>

<%= render 'form' %>

<%= link_to 'Back', customers_path %>

RailsExampleFromClas/app/views/customers/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @customer.name %>
</p>

<p>
  <strong>Discount:</strong>
  <%= @customer.discount %>
</p>

<%= link_to 'New Order', new_order_path(customer: @customer) %>

<%= link_to 'Edit', edit_customer_path(@customer) %> |
<%= link_to 'Back', customers_path %>

RailsExampleFromClas/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>RailsExampleFromClas</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

RailsExampleFromClas/app/views/orders/_form.html.erb
<%= form_for(@order) do |f| %>
  <% if @order.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@order.errors.count, "error") %> prohibited this order from being saved:</h2>

      <ul>
      <% @order.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :customer_id %><br>
    <%= f.number_field :customer_id %>
  </div>
  <div class="field">
    <%= f.label :placed_on %><br>
    <%= f.text_field :placed_on %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

RailsExampleFromClas/app/views/orders/edit.html.erb
<h1>Editing order</h1>

<%= render 'form' %>

<%= link_to 'Show', @order %> |
<%= link_to 'Back', orders_path %>

RailsExampleFromClas/app/views/orders/index.html.erb
<h1>Listing orders</h1>

<table>
  <thead>
    <tr>
      <th>Customer</th>
      <th>Placed on</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @orders.each do |order| %>
      <tr>
        <td><%= order.customer_id %></td>
        <td><%= order.placed_on %></td>
        <td><%= link_to 'Show', order %></td>
        <td><%= link_to 'Edit', edit_order_path(order) %></td>
        <td><%= link_to 'Destroy', order, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Order', new_order_path %>

RailsExampleFromClas/app/views/orders/new.html.erb
<h1>New order</h1>

<%= render 'form' %>

<%= link_to 'Back', orders_path %>

RailsExampleFromClas/app/views/orders/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Customer:</strong>
  <%= @order.customer_id %>
</p>

<p>
  <strong>Placed on:</strong>
  <%= @order.placed_on %>
</p>

<%= link_to 'Edit', edit_order_path(@order) %> |
<%= link_to 'Back', orders_path %>

RailsExampleFromClas/app/views/pumpkins/_form.html.erb
<%= form_for(@pumpkin) do |f| %>
  <% if @pumpkin.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@pumpkin.errors.count, "error") %> prohibited this pumpkin from being saved:</h2>

      <ul>
      <% @pumpkin.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :color %><br>
    <%= f.text_field :color %>
  </div>
  <div class="field">
    <%= f.label :size %><br>
    <%= f.number_field :size %>
  </div>
  <div class="field">
    <%= f.label :price %><br>
    <%= f.text_field :price %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

RailsExampleFromClas/app/views/pumpkins/edit.html.erb
<h1>Editing pumpkin</h1>

<%= render 'form' %>

<%= link_to 'Show', @pumpkin %> |
<%= link_to 'Back', pumpkins_path %>

RailsExampleFromClas/app/views/pumpkins/index.html.erb
<h1>Listing pumpkins</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Color</th>
      <th>Size</th>
      <th>Price</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @pumpkins.each do |pumpkin| %>
      <tr>
        <td><%= pumpkin.name %></td>
        <td><%= pumpkin.color %></td>
        <td><%= pumpkin.size %></td>
        <td><%= pumpkin.price %></td>
        <td><%= link_to 'Show', pumpkin %></td>
        <td><%= link_to 'Edit', edit_pumpkin_path(pumpkin) %></td>
        <td><%= link_to 'Destroy', pumpkin, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Pumpkin', new_pumpkin_path %>

RailsExampleFromClas/app/views/pumpkins/new.html.erb
<h1>New pumpkin</h1>

<%= render 'form' %>

<%= link_to 'Back', pumpkins_path %>

RailsExampleFromClas/app/views/pumpkins/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @pumpkin.name %>
</p>

<p>
  <strong>Color:</strong>
  <%= @pumpkin.color %>
</p>

<p>
  <strong>Size:</strong>
  <%= @pumpkin.size %>
</p>

<p>
  <strong>Price:</strong>
  <%= @pumpkin.price %>
</p>

<%= link_to 'Edit', edit_pumpkin_path(@pumpkin) %> |
<%= link_to 'Back', pumpkins_path %>