HTW/config/routes.rb
Rails.application.routes.draw do
  resources :line_items

  resources :orders

  resources :customers

  resources :pumpkins

  root 'pumpkins#index'

end

HTW/app/models/order.rb
class Order < ActiveRecord::Base
  belongs_to(:customer)
  has_many :lineitems
  has_many :pumpkins, through: :lineitems
end

HTW/app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  before_action :set_order, only: [:show, :edit, :update, :destroy]

  # GET /orders
  # GET /orders.json
  def index
    @orders = Order.all
  end

  # GET /orders/1
  # GET /orders/1.json
  def show    
    #@customer = @order.customer
    #raise params.inspect
    @line_items = LineItem.where(order_id: params[:id]).all
    @total_price = 0

    @line_items.each do |curr|  
      if curr.pumpkin.price
        addPrice = curr.pumpkin.price * curr.amount
        @total_price += addPrice
      end
    end

  end

  # GET /orders/new
  def new
    #raise params.inspect
    if params["customer"]
      @customer = Customer.find(params["customer"])
      @order = @customer.orders.build
    else
      @order = Order.new
    end
  end

  # GET /orders/1/edit
  def edit
  end

  # POST /orders
  # POST /orders.json
  def create
    @order = Order.new(order_params)

    respond_to do |format|
      if @order.save
        format.html { redirect_to @order, notice: 'Order was successfully created.' }
        format.json { render :show, status: :created, location: @order }
      else
        format.html { render :new }
        format.json { render json: @order.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /orders/1
  # PATCH/PUT /orders/1.json
  def update
    respond_to do |format|
      if @order.update(order_params)
        format.html { redirect_to @order, notice: 'Order was successfully updated.' }
        format.json { render :show, status: :ok, location: @order }
      else
        format.html { render :edit }
        format.json { render json: @order.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /orders/1
  # DELETE /orders/1.json
  def destroy
    @order.destroy
    respond_to do |format|
      format.html { redirect_to orders_url, notice: 'Order was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_order
      @order = Order.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def order_params
      params.require(:order).permit(:customer_id, :placed_on, :status, :price, :line_item_id)
    end
end

HTW/app/helpers/orders_helper.rb
module OrdersHelper
end

HTW/app/views/orders/_form.html.erb
<%= form_for(@order) do |f| %>
  <% if @order.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@order.errors.count, "error") %> prohibited this order from being saved:</h2>

      <ul>
      <% @order.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <% if @customer %>
    Order for Customer: <%=@customer.name %><br>
    <%= hidden_field(:order,:customer_id, value: @customer.id) %>
    <% else %>
  <div class="field">
    <%= f.label :customer_id %><br>
    <%= f.number_field :customer_id %>
  </div>
  <% end %>


  <div class="field">
    <%= f.label :placed_on %><br>
    <%= f.date_select :placed_on %>
  </div>
  <div class="field">
    <%= f.label :status %><br>
    <%= f.text_field :status %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

HTW/app/views/orders/edit.html.erb
<h1>Editing order</h1>

<%= render 'form' %>

<%= link_to 'Show', @order %> |
<%= link_to 'Back', orders_path %>

HTW/app/views/orders/index.html.erb
<h1>Listing orders</h1>

<table>
  <thead>
    <tr>
      <th>Customer</th>
      <th>Placed on</th>
      <th>Status</th>
      <th colspan="4"></th>
    </tr>
  </thead>

  <tbody>
    <% @orders.each do |order| %>
      <tr>
        <td><%= order.customer_id %></td>
        <td><%= order.placed_on %></td>
        <td><%= order.status %></td>
        

        <td><%= link_to 'Show', order %></td>
        <td><%= link_to 'Edit', edit_order_path(order) %></td>
        <td><%= link_to 'Destroy', order, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Order', new_order_path %>

HTW/app/views/orders/new.html.erb
<h1>New order</h1>

<%= render 'form' %>

<%= link_to 'add Position', new_line_item_path %>

<%= link_to 'Back', orders_path %>

HTW/app/views/orders/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Customer:</strong>
  <%= @order.customer.name %>
</p>

<p>
  <strong>Placed on:</strong>
  <%= @order.placed_on %>
</p>

<p>
  <strong>Price:</strong>
  <%= @total_price %>€
</p>

<p>
  <strong>Status:</strong>
  <%= @order.status %>
</p>


<table>
  <thead>
    <tr>
      <th>Amount</th>
      <th>Order ID</th>
      <th>Pumpkin ID</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @line_items.each do |line_item| %>
      <tr>
        <td><%= line_item.amount %></td>
        <td><%= line_item.order_id %></td>
        <td><%= line_item.pumpkin_id %></td>
        	
      </tr>
    <% end %>
  </tbody>
</table>



<%= link_to 'Edit', edit_order_path(@order) %> |
<%= link_to 'Back', orders_path %>